<?php

namespace ContainerPtXowKi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q7R9jdwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q7R9jdw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q7R9jdw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fileRepository' => ['privates', 'App\\Repository\\FileRepository', 'getFileRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'fileRepository' => 'App\\Repository\\FileRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
